Repository AY2425S1-CS2113-T11-3/tp, pull requests merged in 2024-11, with the labels that each got.

#120 A-AddRentalTransaction Features Improvements
  META-INF/MANIFEST.MF
  data/carData.txt
  data/customerData.txt
  data/transactionData.txt
  docs/UserGuide.md
  src/main/java/customer/Customer.java
  src/main/java/customer/CustomerList.java
  src/main/java/exceptions/CustomerException.java
  src/main/java/file/CustomerFile.java
  src/main/java/file/TransactionFile.java
  src/main/java/parser/CustomerParser.java
  src/main/java/parser/HelpParser.java
  src/main/java/parser/Parser.java
  src/main/java/parser/TransactionParser.java
  src/main/java/seedu/clirental/CliRental.java
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
  src/test/java/customer/CustomerTest.java
  src/test/java/file/CustomerFileTest.java
  src/test/java/file/TransactionFileTest.java
  src/test/java/parser/CustomerParserTest.java
  src/test/java/parser/ParserTest.java
  src/test/java/transaction/TransactionListTest.java
  src/test/java/transaction/TransactionTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#124 A-MarkCompletedTx & A-UnmarkCompleteTx
  docs/UserGuide.md
  src/main/java/transaction/TransactionList.java
Labels: priority.Medium

#128 A-DG-UG-Update
  data/carData.txt
  data/customerData.txt
  data/transactionData.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddCustomerSequence.png
  docs/images/CLiRental.png
  docs/images/CarFileLoader.png
  src/main/java/car/Car.java
  src/main/java/customer/Customer.java
  src/main/java/customer/CustomerList.java
  src/main/java/file/CarFile.java
  src/main/java/file/TransactionFile.java
  src/main/java/parser/CustomerParser.java
  src/main/java/transaction/Transaction.java
  src/test/java/file/TransactionFileTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/carData.txt
  text-ui-test/data/customerData.txt
  text-ui-test/data/transactionData.txt
  text-ui-test/input.txt
Labels: type.Task

#130 A-AddRentalTX Improvement
  src/main/java/transaction/Transaction.java
  src/test/java/transaction/TransactionTest.java
Labels: priority.Medium

#207 Improve A-AddRental and Transaction_ID generation
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
  src/test/java/transaction/TransactionTest.java
Labels: priority.High

#213 A-StoreTxId
  docs/UserGuide.md
  src/main/java/file/TransactionFile.java
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
  src/test/java/file/TransactionFileTest.java
Labels: priority.Medium

#215 Fixed Tx ID saving and loading
  src/main/java/file/TransactionFile.java
  src/main/java/parser/TransactionParser.java
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
  src/test/java/file/TransactionFileTest.java
  src/test/java/transaction/TransactionListTest.java
  src/test/java/transaction/TransactionTest.java
Labels: priority.High

#221 A-RexCodeQuality
  docs/DeveloperGuide.md
  docs/UML/AddCustomerSequence.puml
  docs/UML/CLiRental.puml
  docs/UML/CarFileLoader.puml
  docs/UML/ListCarsSequence.puml
  docs/UserGuide.md
  docs/diagrams/Overall.puml
  docs/images/CarFileLoader.png
  src/main/java/exceptions/CarException.java
  src/main/java/exceptions/CustomerException.java
  src/main/java/exceptions/TransactionException.java
  src/main/java/file/CarFile.java
  src/main/java/file/CustomerFile.java
  src/main/java/file/FileHandler.java
  src/main/java/file/TransactionFile.java
  src/main/java/parser/CustomerParser.java
  src/main/java/transaction/Transaction.java
  src/test/java/customer/CustomerListTest.java
  src/test/java/file/testFileForCar.txt
  src/test/java/file/testFileForCustomer.txt
  src/test/java/file/testFileForTransaction.txt
Labels: type.Enhancement

#229 A-RexV2.1
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UML/AddCustomerSequence.puml
  docs/UML/FileHandlerClassDiagram.puml
  docs/UML/ListCarsSequence.puml
  docs/images/AddCustomerSequence.png
  docs/images/ArchitectureDiagram.drawio.png
  docs/images/CarFileLoader.png
  docs/images/FileHandlerClassDiagram.png
  docs/images/ListCarsSequence.png
  docs/team/Rex.png
  docs/team/rexkoh425.md
  src/main/java/file/CarFile.java
  src/main/java/file/CustomerFile.java
  src/main/java/file/TransactionFile.java
  src/main/java/transaction/TransactionList.java
  src/test/java/file/CarFileTest.java
  src/test/java/file/CustomerFileTest.java
  src/test/java/file/TransactionFileTest.java
  src/test/java/file/testFileForCar.txt
  src/test/java/file/testFileForCustomer.txt
Labels: type.Task

#227 remove-user is case insensitive now
  src/main/java/customer/CustomerList.java
Labels: priority.Medium

#231 Update UG to be more detailed. Added junittest for remove-user. Updated remove-user for empty customer list. Added PPP
  docs/UserGuide.md
  docs/team/SemiColonKen.md
  src/main/java/customer/CustomerList.java
  src/test/java/customer/CustomerListTest.java
Labels: priority.Medium

#236 Update Junit
  src/main/java/car/CarList.java
  src/main/java/transaction/TransactionList.java
  src/test/java/file/TransactionFileTest.java
  src/test/java/transaction/TransactionListTest.java
Labels: priority.Low

#237 Update Junit
  src/test/java/file/CarFileTest.java
  src/test/java/file/CustomerFileTest.java
  src/test/java/file/TransactionFileTest.java
Labels: priority.Low

#238 A-JunitFixAge
  docs/DeveloperGuide.md
  src/main/java/customer/Customer.java
  src/main/java/exceptions/CustomerException.java
  src/main/java/parser/CustomerParser.java
Labels: priority.Medium

#242 Update formatting
  docs/team/rexkoh425.md
Labels: priority.Low
