Repository AY2425S1-CS2113-T11-3/tp, pull requests merged in 2024-10, with the labels that each got.

#54 A-AddCustomers
  src/main/java/customer/Customer.java
  src/main/java/customer/CustomerList.java
  src/main/java/exceptions/CustomerException.java
  src/main/java/parser/Parser.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/customer/CustomerListTest.java
  src/test/java/customer/CustomerTest.java
  src/test/java/parser/ParserTest.java
  src/test/java/seedu/duke/DukeTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.feature

#55 A-AddCustomerUG
  build.gradle
  docs/UserGuide.md
  src/main/java/customer/Customer.java
  src/main/java/parser/Parser.java
  src/main/java/seedu/clirental/CliRental.java
  src/test/java/seedu/clirental/CliRental.java
Labels: type.Task

#64 A-ListAllCustomers & A-RemoveTransaction
  docs/AboutUs.md
  docs/team/liuhao.md
  src/main/java/customer/CustomerList.java
  src/main/java/parser/Parser.java
  src/main/java/parser/TransactionParser.java
  src/main/java/transcation/Transaction.java
  src/main/java/transcation/TransactionList.java
Labels: priority.High, type.feature

#66 A-ListRentalCars
  docs/UserGuide.md
  src/main/java/car/CarList.java
  src/test/java/car/CarListTest.java
  src/test/java/customer/CustomerListTest.java
Labels: type.feature

#75 A-ListRentalCarsBugFix
  src/main/java/parser/Parser.java
Labels: type.Task

#84 A-AddRental
  src/main/java/parser/Parser.java
  src/main/java/parser/TransactionParser.java
  src/main/java/rental/RentalSystem.java
  src/main/java/rental/RentalTransaction.java
  src/main/java/transcation/Transaction.java
  src/main/java/transcation/TransactionList.java
Labels: type.Task

#88 A-RentedStatus
  docs/UserGuide.md
  src/main/java/car/Car.java
  src/main/java/car/CarList.java
  src/main/java/seedu/clirental/CliRental.java
  src/test/java/car/CarTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/testingCommands
Labels: priority.High

#95 A-CarRentalStatus
  build.gradle
  src/main/java/car/Car.java
  src/main/java/car/CarList.java
  src/main/java/exceptions/CarException.java
  src/main/java/parser/CarParser.java
  src/main/java/parser/Parser.java
  src/main/java/parser/TransactionParser.java
  src/main/java/seedu/clirental/CliRental.java
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
  src/test/java/car/CarListTest.java
  src/test/java/car/CarTest.java
  src/test/java/parser/CarParserTest.java
  src/test/java/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#99 fix remove-tx issues and exceptions
  src/main/java/customer/CustomerList.java
  src/main/java/exceptions/CarException.java
  src/main/java/parser/CarParser.java
  src/main/java/parser/Parser.java
  src/main/java/parser/TransactionParser.java
  src/main/java/transaction/TransactionList.java
  src/test/java/car/CarTest.java
  src/test/java/customer/CustomerListTest.java
Labels: priority.High

#100 mark/unmark tx completed; show completed/uncompleted tx etc.
  src/main/java/car/Car.java
  src/main/java/exceptions/CarException.java
  src/main/java/parser/HelpParser.java
  src/main/java/parser/Parser.java
  src/main/java/parser/TransactionParser.java
  src/main/java/seedu/clirental/CliRental.java
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#104 A-ShowAllRented
  src/main/java/car/CarList.java
  src/main/java/exceptions/CarException.java
  src/main/java/parser/Parser.java
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
Labels: type.Task

#109 A-SaveFile
  build.gradle
  docs/DeveloperGuide.md
  docs/UML/AddCustomerSequence.png
  docs/UML/AddCustomerSequence.puml
  docs/UML/CLiRental.png
  docs/UML/CLiRental.puml
  docs/UML/CarFileLoader.png
  docs/UML/CarFileLoader.puml
  docs/UserGuide.md
  src/main/java/car/Car.java
  src/main/java/car/CarList.java
  src/main/java/customer/Customer.java
  src/main/java/customer/CustomerList.java
  src/main/java/exceptions/CarException.java
  src/main/java/exceptions/CustomerException.java
  src/main/java/exceptions/TransactionException.java
  src/main/java/file/CarFile.java
  src/main/java/file/CustomerFile.java
  src/main/java/file/FileHandler.java
  src/main/java/file/TransactionFile.java
  src/main/java/parser/CustomerParser.java
  src/main/java/seedu/clirental/CliRental.java
  src/main/java/transaction/Transaction.java
  src/main/java/transaction/TransactionList.java
  src/test/java/customer/CustomerListTest.java
  src/test/java/customer/CustomerTest.java
  src/test/java/file/CarFileTest.java
  src/test/java/file/CustomerFileTest.java
  src/test/java/file/TransactionFileTest.java
  src/test/java/parser/CustomerParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/testingCommands
Labels: type.Task
